"""Agentic RAG — iterative multi-hop search (Phase 4).

After each search round the LLM judges whether the retrieved context is
sufficient to answer the original query.  If not, it generates a
follow-up query and searches again.  Up to ``max_rounds`` iterations.

Each round collects **two types of context**:

* **Vector sources** — chunks from Milvus (dense + sparse search)
* **Graph data** — entities, relations, and KG-linked chunks from
  ``LightRAG.aquery_data()`` (no LLM call — just graph traversal)

The judge sees both, leading to better follow-up queries.  The final
answer is generated by ``LightRAG.aquery()`` which uses the full KG
pipeline (keyword extraction → graph search → LLM synthesis).

No LangGraph / CrewAI — plain Python async loop.
"""

from __future__ import annotations

import json
import time
from typing import Any

from loguru import logger

from src.config import settings
from src.llm_client import LLMClient
from src.models.search import AgenticRoundStat, SearchResponse, SourceCitation
from src.retrieval.hybrid_search import HybridSearcher, SearchMode

# ── prompts ──────────────────────────────────────────────────────────

_JUDGE_PROMPT = (
    "You are a search quality judge. Given the original query, the "
    "retrieved text chunks, AND the knowledge graph data (entities and "
    "relationships), decide whether there is enough information to fully "
    "answer the query.\n\n"
    "Return ONLY valid JSON (no markdown fences):\n"
    '{"sufficient": true/false, "follow_up_query": "...", "reason": "..."}\n\n'
    "Rules:\n"
    "- If sufficient, set follow_up_query to an empty string.\n"
    "- If not sufficient, write a concise follow-up search query that "
    "would retrieve the missing information.\n"
    "- The follow-up query must be different from previous queries.\n"
    "- Consider both the text chunks AND the graph entities/relationships "
    "when judging sufficiency."
)

# ── helpers ──────────────────────────────────────────────────────────


def _deduplicate_sources(sources: list[SourceCitation]) -> list[SourceCitation]:
    """Remove duplicate sources by chunk_id, preserving order."""
    seen: set[str] = set()
    unique: list[SourceCitation] = []
    for src in sources:
        if src.chunk_id not in seen:
            seen.add(src.chunk_id)
            unique.append(src)
    return unique


def _build_chunks_str(sources: list[SourceCitation], max_chars: int = 4000) -> str:
    """Concatenate source contents, truncated to max_chars."""
    parts: list[str] = []
    total = 0
    for src in sources:
        if total + len(src.content) > max_chars:
            remaining = max_chars - total
            if remaining > 100:
                parts.append(src.content[:remaining])
            break
        parts.append(src.content)
        total += len(src.content)
    return "\n---\n".join(parts)


def _build_graph_str(graph_data: dict, max_chars: int = 2000) -> str:
    """Format graph entities and relations for the judge prompt."""
    data = graph_data.get("data", graph_data)
    parts: list[str] = []

    entities = data.get("entities", [])
    if entities:
        ent_lines = []
        for e in entities[:20]:
            name = e.get("entity_name", "")
            etype = e.get("entity_type", "")
            desc = e.get("description", "")[:120]
            ent_lines.append(f"  - {name} ({etype}): {desc}")
        parts.append("Entities:\n" + "\n".join(ent_lines))

    relations = data.get("relationships", [])
    if relations:
        rel_lines = []
        for r in relations[:20]:
            src = r.get("src_id", "")
            tgt = r.get("tgt_id", "")
            desc = r.get("description", "")[:120]
            rel_lines.append(f"  - {src} → {tgt}: {desc}")
        parts.append("Relationships:\n" + "\n".join(rel_lines))

    result = "\n\n".join(parts)
    return result[:max_chars] if len(result) > max_chars else result


_DEFAULT_HL_KEYWORD_LIMIT = 30


def _accumulated_hl_keywords(
    graph_data: dict, limit: int = _DEFAULT_HL_KEYWORD_LIMIT,
) -> list[str]:
    """Top-N entity names from accumulated graph data, dedup-preserving order.

    Entities in ``graph_data`` are already deduplicated by name (see
    ``_merge_graph_data``); their order tracks the LightRAG retrieval
    ranking from the round that first surfaced each one.  We trim to
    ``limit`` to keep the keyword list focused — too many keywords
    dilute the retrieval signal LightRAG normally derives via its own
    keyword-extraction LLM call.
    """
    data = graph_data.get("data", graph_data)
    names: list[str] = []
    seen: set[str] = set()
    for ent in data.get("entities", []):
        name = (ent.get("entity_name") or "").strip()
        if not name or name in seen:
            continue
        seen.add(name)
        names.append(name)
        if len(names) >= limit:
            break
    return names


def _build_enriched_query(query: str, follow_ups: list[str]) -> str:
    """Original query + appended LLM-judge follow-ups.

    Empty/no-follow-up case returns the original verbatim — we never
    add a hollow "Related sub-queries:" header.  Duplicate follow-ups
    are dropped because a few judge implementations occasionally
    re-emit a previous query.
    """
    if not follow_ups:
        return query
    seen: set[str] = {query}
    extras: list[str] = []
    for fu in follow_ups:
        fu = (fu or "").strip()
        if not fu or fu in seen:
            continue
        seen.add(fu)
        extras.append(fu)
    if not extras:
        return query
    return query + "\n\nRelated sub-queries:\n- " + "\n- ".join(extras)


def _merge_graph_data(accumulated: dict, new: dict) -> dict:
    """Merge graph data from multiple rounds, deduplicating by name/id."""
    if not accumulated:
        return new
    if not new:
        return accumulated

    acc_data = accumulated.get("data", accumulated)
    new_data = new.get("data", new)

    # Deduplicate entities by entity_name
    seen_ents: set[str] = set()
    merged_entities: list[dict] = []
    for e in acc_data.get("entities", []) + new_data.get("entities", []):
        name = e.get("entity_name", "")
        if name and name not in seen_ents:
            seen_ents.add(name)
            merged_entities.append(e)

    # Deduplicate relations by src_id+tgt_id
    seen_rels: set[str] = set()
    merged_relations: list[dict] = []
    for r in acc_data.get("relationships", []) + new_data.get("relationships", []):
        key = f"{r.get('src_id', '')}→{r.get('tgt_id', '')}"
        if key not in seen_rels:
            seen_rels.add(key)
            merged_relations.append(r)

    return {"data": {"entities": merged_entities, "relationships": merged_relations}}


async def _judge_context(
    client: LLMClient,
    query: str,
    sources: list[SourceCitation],
    graph_data: dict,
) -> dict:
    """Ask LLM whether the accumulated context is sufficient.

    The judge sees both vector-search chunks AND knowledge graph data
    (entities, relationships) for a more informed decision.

    Returns ``{"sufficient": bool, "follow_up_query": str, "reason": str}``.
    On any failure returns ``{"sufficient": True}`` to stop the loop.
    """
    chunks_ctx = _build_chunks_str(sources)
    graph_ctx = _build_graph_str(graph_data)

    context_parts = [f"Text chunks ({len(sources)}):\n{chunks_ctx}"]
    if graph_ctx:
        context_parts.append(f"Knowledge graph:\n{graph_ctx}")
    full_context = "\n\n".join(context_parts)

    try:
        resp = await client.chat(
            model=settings.effective_llm_model,
            messages=[
                {"role": "system", "content": _JUDGE_PROMPT},
                {
                    "role": "user",
                    "content": (
                        f"Original query: {query}\n\n"
                        f"Retrieved context:\n{full_context}"
                    ),
                },
            ],
        )
        raw = resp["message"]["content"].strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        parsed = json.loads(raw)
        return {
            "sufficient": bool(parsed.get("sufficient", True)),
            "follow_up_query": str(parsed.get("follow_up_query", "")),
            "reason": str(parsed.get("reason", "")),
        }
    except Exception as exc:
        logger.warning("agentic judge failed, stopping loop: {err}", err=exc)
        return {"sufficient": True, "follow_up_query": "", "reason": str(exc)}


# ── main function ────────────────────────────────────────────────────


async def agentic_search(
    searcher: HybridSearcher,
    query: str,
    llm_client: LLMClient,
    *,
    max_rounds: int = 3,
    mode: SearchMode = "hybrid",
    department: str | None = None,
    top_k: int = 10,
    user_id: str | None = None,
    doc_type_filter: str | None = None,
    created_after: int | None = None,
    created_before: int | None = None,
    chunk_top_k: int = 20,
    max_entity_tokens: int = 6000,
    max_relation_tokens: int = 8000,
    max_total_tokens: int = 30000,
    response_type: str = "Multiple Paragraphs",
    include_references: bool = False,
) -> SearchResponse:
    """Iterative multi-hop search with LLM judgment loop.

    Each round:
      1. Vector search (Milvus) → chunks  (skip_rag=True, no LLM)
      2. Graph query (LightRAG aquery_data) → entities + relations (no LLM)
      3. Judge (LLM) sees both → sufficient? → follow-up query

    Final answer:
      LightRAG aquery() with original query → full KG pipeline + LLM
    """
    t0 = time.monotonic()
    all_sources: list[SourceCitation] = []
    all_graph_data: dict = {}
    follow_up_queries: list[str] = []
    round_stats: list[AgenticRoundStat] = []
    current_query = query
    rounds = 0

    search_kwargs: dict[str, Any] = dict(
        mode=mode,
        department=department,
        top_k=top_k,
        user_id=user_id,
        doc_type_filter=doc_type_filter,
        created_after=created_after,
        created_before=created_before,
        chunk_top_k=chunk_top_k,
        max_entity_tokens=max_entity_tokens,
        max_relation_tokens=max_relation_tokens,
        max_total_tokens=max_total_tokens,
        response_type=response_type,
        include_references=include_references,
        decompose=False,
        skip_rag=True,  # skip LLM in intermediate rounds
    )

    graph_kwargs = dict(
        mode=mode,
        top_k=top_k,
        chunk_top_k=chunk_top_k,
        max_entity_tokens=max_entity_tokens,
        max_relation_tokens=max_relation_tokens,
        max_total_tokens=max_total_tokens,
    )

    for round_num in range(1, max_rounds + 1):
        rounds = round_num

        # snapshot pre-aggregation counts for delta tracking
        prev_sources_n = len(all_sources)
        prev_entities_n = len(
            all_graph_data.get("data", {}).get("entities", [])
        )
        prev_relations_n = len(
            all_graph_data.get("data", {}).get("relationships", [])
        )

        # a. vector search (no RAG LLM call)
        resp = await searcher.search(current_query, **search_kwargs)
        all_sources.extend(resp.sources)
        all_sources = _deduplicate_sources(all_sources)

        # b. graph data (entities + relations, no LLM call)
        graph_data = await searcher.query_graph_data(
            current_query, **graph_kwargs,
        )
        all_graph_data = _merge_graph_data(all_graph_data, graph_data)

        entities_count = len(
            all_graph_data.get("data", {}).get("entities", [])
        )
        relations_count = len(
            all_graph_data.get("data", {}).get("relationships", [])
        )

        new_sources = len(all_sources) - prev_sources_n
        new_entities = entities_count - prev_entities_n
        new_relations = relations_count - prev_relations_n

        logger.info(
            "agentic round={round}  query={q!r}  sources={src} (+{ns})  "
            "entities={ent} (+{ne})  relations={rel} (+{nr})",
            round=round_num, q=current_query,
            src=len(all_sources), ent=entities_count, rel=relations_count,
            ns=new_sources, ne=new_entities, nr=new_relations,
        )

        # Stage G: short-circuit on barren follow-up rounds.  If round N
        # (N>1) didn't add a single chunk, entity, or relation the judge
        # has nothing new to evaluate either — skip the LLM call and
        # exit.  Round 1 always proceeds to judge (initial assessment).
        if (
            round_num > 1
            and new_sources == 0
            and new_entities == 0
            and new_relations == 0
        ):
            logger.info(
                "agentic round={round}  early exit — no new info from "
                "follow-up query  skipping judge",
                round=round_num,
            )
            round_stats.append(AgenticRoundStat(
                round=round_num,
                query=current_query,
                new_sources=new_sources,
                new_entities=new_entities,
                new_relations=new_relations,
                sufficient=None,  # judge skipped
                judge_reason="no new info",
            ))
            break

        # c. judge (LLM call) — sees both chunks and graph data
        judgment = await _judge_context(
            llm_client, query, all_sources, all_graph_data,
        )

        logger.info(
            "agentic judge  sufficient={suf}  reason={reason!r}  "
            "follow_up={fup!r}",
            suf=judgment["sufficient"],
            reason=judgment.get("reason", ""),
            fup=judgment.get("follow_up_query", ""),
        )

        round_stats.append(AgenticRoundStat(
            round=round_num,
            query=current_query,
            new_sources=new_sources,
            new_entities=new_entities,
            new_relations=new_relations,
            sufficient=bool(judgment["sufficient"]),
            judge_reason=str(judgment.get("reason", "")),
        ))

        if judgment["sufficient"]:
            break

        follow_up = judgment["follow_up_query"]
        if not follow_up or follow_up == current_query:
            break
        follow_up_queries.append(follow_up)
        current_query = follow_up

    # d. final answer: LightRAG full pipeline (graph + LLM synthesis)
    #
    # Stage F: feed accumulated context back into the final synthesis
    # so the rounds aren't wasted.  Two channels:
    #   * `hl_keywords` — top entity names from the merged graph data
    #     across all rounds.  LightRAG normally derives these via an
    #     LLM keyword-extraction step; supplying them directly skips
    #     that LLM call AND grounds the final retrieval in what the
    #     prior probes actually found.
    #   * `enriched_query` — original query plus the LLM-judge's
    #     follow-up queries appended as sub-queries.  Widens keyword
    #     coverage in the retrieval channel without changing
    #     QueryParam semantics.
    enriched_query = _build_enriched_query(query, follow_up_queries)
    hl_keywords = _accumulated_hl_keywords(all_graph_data)

    answer = await searcher._ask_rag(
        enriched_query, mode,
        top_k=top_k,
        chunk_top_k=chunk_top_k,
        max_entity_tokens=max_entity_tokens,
        max_relation_tokens=max_relation_tokens,
        max_total_tokens=max_total_tokens,
        response_type=response_type,
        include_references=include_references,
        hl_keywords=hl_keywords or None,
    )

    latency_ms = (time.monotonic() - t0) * 1000.0

    logger.info(
        "agentic done  rounds={rounds}  total_sources={n}  "
        "follow_ups={fups}  hl_keywords={hl}  latency_ms={ms:.1f}",
        rounds=rounds, n=len(all_sources),
        fups=follow_up_queries, hl=len(hl_keywords),
        ms=latency_ms,
    )

    return SearchResponse(
        query=query,
        answer=answer,
        mode=mode,
        sources=all_sources,
        latency_ms=latency_ms,
        agentic_rounds=rounds,
        follow_up_queries=follow_up_queries if follow_up_queries else None,
        agentic_round_stats=round_stats if round_stats else None,
    )
